DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.15
  min_vel_x: 0.00

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_trans_vel:  0.15
  min_trans_vel:  0.05

  max_rot_vel: 0.3
  min_rot_vel: 0.12

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 2.0 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 5.0
  vx_samples: 10
  vy_samples: 0
  vth_samples: 25
  controller_frequency: 10.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.025

# Trajectory Scoring Parameters
  path_distance_bias: 70
  goal_distance_bias: 40
  occdist_scale: 0.2
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  meter_scoring: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.025
  oscillation_reset_angle: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  publish_cost_grid: true
  prune_plan: true
  
 
