shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 15.0
controller_patience: 25.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'


# apply reset to obstacle and range sensor layers
super_conservative_reset:
  reset_distance: 3.0
  layer_names:
    - obstacle_layer
    - range_sensor_layer

rotate_recovery:
  reset_distance: 2.0
  layer_names:
    - obstacle_layer
    - range_sensor_layer

conservative_reset:
  reset_distance: 1.5
  layer_names:
    - obstacle_layer
    - range_sensor_layer

aggressive_reset:
  reset_distance: 0.5
  layer_names:
    - obstacle_layer
    - range_sensor_layer
